Repository luksan47/mars, pull requests merged in 2019-10, with the labels that each got.

#29 Write a contributor's guide
  CONTRIBUTING.md
Labels: documentation

#64 Issue #14: Printing module: implement free pages functionality
  app/Http/Controllers/PrintController.php
  resources/lang/en/print.php
  resources/lang/hu/print.php
  resources/views/print/app.blade.php
  resources/views/print/free.blade.php
  routes/web.php
Labels: enhancement

#69 Fix validation error, fix Eng and Hun translations for print.modify
  app/Http/Controllers/PrintController.php
  resources/lang/en/print.php
  resources/lang/hu/print.php
  resources/lang/hu/validation.php
Labels: bug
